name: Build APK (Simple)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.3'
        channel: 'stable'
    
    - name: Clean build
      run: flutter clean
    
    - name: Get dependencies  
      run: flutter pub get
    
    - name: Build APK (Simple)
      run: flutter build apk --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: posture-health-app-simple
        path: build/app/outputs/flutter-apk/app-release.apk
